# Generated by Django 3.1.7 on 2021-10-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_city_donation_thana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='last_donation',
            field=models.DateTimeField(),
        ),
    ]
