# Generated by Django 3.1.7 on 2021-10-08 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_donation_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='bloodgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bloodgroup'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
