# Generated by Django 3.1.7 on 2021-11-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20211030_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_donation',
        ),
    ]
