# Generated by Django 3.1.7 on 2021-11-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20211108_1514'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donation',
            table='doner',
        ),
    ]
