# Generated by Django 3.1.7 on 2021-11-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20211108_1543'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donation',
            table=None,
        ),
    ]
