# Generated by Django 3.1.7 on 2021-11-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_requestchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestchange',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
